## https://developers.cloudflare.com/access/ssh/ssh-guide/#2-authenticate-the-cloudflare-daemon
## Host [your hostname]
##   ProxyCommand /usr/local/bin/cloudflared access ssh --hostname %h

- name: Create file {{ ssh_config_file }} if it does not exists
  ansible.builtin.file:
    path: "{{ ssh_config_file }}"
    state: touch
    mode: "644"

- name: Check if {{ item }} is added to local ssh config
  ansible.builtin.shell: grep -c "^Host {{ item }}." {{ ssh_config_file }} || true
  register: test_grep

- name: Add proxy config for {{ item }} is added to local ssh config
  when: test_grep.stdout == "0"
  ansible.builtin.lineinfile:
    dest: "{{ ssh_config_file }}"
    line: "Host {{ item }}.{{ external_domain }}\n   ProxyCommand /usr/bin/cloudflared access ssh --hostname %h"
